[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312"]

[tool.ruff]
line-length = 88
select = ["E","F","I","UP","B","ANN"] 
ignore = []
target-version = "py310"

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_ignores = true
no_implicit_optional = true

