services:
  ragit:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./data:/data/
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

